### ISSUE TITLE
Is mjml actually being used?

### ISSUE THREAD

**Issue by JakeIwen** [BounceTribe/bt-api#1]
https://github.com/BounceTribe/bt-api/blob/master/src/emails/feedbackReceived.js
https://github.com/BounceTribe/bt-api/blob/master/src/emails/friendRequestAccepted.js

mjml is defined at the beginning of the page and never referenced nor exported. It looks like a HTML conversion of the mjml may be getting used instead. 

Is this intended?

**Comment by carlpeaslee** [comment]
It is not being used. And it shouldn’t be imported. Probably there should
instead be a script or something somewhere that takes the original and
converts it and that could get run whenever we wanted.

**Comment by JakeIwen** [comment]
Sounds good, thank you. 
Also, is this ever run locally for testing? 
Want to make sure things work before pushing.
There is nothing in .gitignore suggesting that ENV variables have been set up locally.

I am having trouble tracing the stack for sending an email.
For example:
I can see that an email with subject "Welcome to bouncetribe" was sent out yesterday via the Mailgun dashboard. 
I cannot find the words "Welcome to Bouncetribe" (within this context) anywhere in either BT repo. Where is this being sourced? How can I trace the "welcome to bouncetribe" email example?

**Comment by carlpeaslee** [comment]
I don’t it ever is run locally— which isn’t ideal. Would probably be
helpful to set up that capability.

**Comment by JakeIwen** [comment]
Also @carlpeaslee could I get added to this repo for write access?
